"""add user class

Revision ID: 62d901b566ae
Revises: 7fc09b455d5f
Create Date: 2025-12-30 16:00:37.768291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d901b566ae'
down_revision: Union[str, Sequence[str], None] = '7fc09b455d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('sold')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.BOOLEAN(), nullable=False))

    op.drop_table('users')
    # ### end Alembic commands ###
