"""Update relationship event and sponsor class

Revision ID: 7fc09b455d5f
Revises: bdac3616aed8
Create Date: 2025-12-30 13:49:37.559933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc09b455d5f'
down_revision: Union[str, Sequence[str], None] = 'bdac3616aed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('show',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('show',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
